window.WH = window.WH || {};
WH.api = WH.api || {};

(function() {
  function mockDelay(ms = 400) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

const WAREHOUSE_MOCK_DATA = {
  warehouses: [
    {
      warehouse: 1,
      warehouseName: "WR #2",
      measurement: "Meter",
      polygon: [
        { x: 0, z: 60 },
        { x: 100, z: 60 },
        { x: 100, z: 0 },
        { x: 400, z: 0 },
        { x: 400, z: 180 },
        { x: 280, z: 180 },
        { x: 280, z: 620 },
        { x: 0, z: 620 },
      ],
      areas: [
        {
          area: 2,
          areaName: "MF",
          floor: 1,
          measurement: "Meter",
          polygon: [
            { x: 0, z: 60 },
            { x: 100, z: 60 },
            { x: 100, z: 0 },
            { x: 400, z: 0 },
            { x: 400, z: 180 },
            { x: 0, z: 180 },
          ],
          rows: [
            {
              row: 1,
              rowName: "MF-01",
              direction: "LeftToRight",
              align: "Bottom",
              measurement: "Meter",
              polygon: [
                { x: 110, z: 0 },
                { x: 110, z: 15 },
                { x: 350, z: 15 },
                { x: 350, z: 0 },
              ],
              levels: [
                {
                  level: 1,
                  levelName: "MF-01-01",
                  cells: [
                    {
                      place: 1,
                      number: "MF-01-01-01",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 2,
                      number: "MF-01-01-02",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 3,
                      number: "MF-01-01-03",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 4,
                      number: "MF-01-01-04",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 5,
                      number: "MF-01-01-05",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                  ],
                },
                {
                  level: 2,
                  levelName: "MF-01-02",
                  cells: [
                    {
                      place: 1,
                      number: "MF-01-02-01",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 2,
                      number: "MF-01-02-02",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 0,
                    },
                    {
                      place: 3,
                      number: "MF-01-02-03",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 4,
                      number: "MF-01-02-04",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                  ],
                },
              ],
            },
            {
              row: 2,
              rowName: "MF-02",
              direction: "BottomToTop",
              align: "Left",
              measurement: "Meter",
              polygon: [
                { x: 0, z: 75 },
                { x: 15, z: 75 },
                { x: 15, z: 150 },
                { x: 0, z: 150 },
              ],
              levels: [
                {
                  level: 1,
                  levelName: "MF-02-01",
                  cells: [
                    {
                      place: 1,
                      number: "MF-02-01-01",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 2,
                      number: "MF-02-01-02",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 3,
                      number: "MF-02-01-03",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                  ],
                },
                {
                  level: 2,
                  levelName: "MF-02-02",
                  cells: [
                    {
                      place: 1,
                      number: "MF-02-02-01",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 2,
                      number: "MF-02-02-02",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 3,
                      number: "MF-02-02-03",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                  ],
                },
              ],
            },
            {
              row: 3,
              rowName: "MF-03",
              direction: "RightToLeft",
              align: "Top",
              measurement: "Meter",
              polygon: [
                { x: 110, z: 45 },
                { x: 110, z: 60 },
                { x: 300, z: 60 },
                { x: 300, z: 45 },
              ],
              levels: [
                {
                  level: 1,
                  levelName: "MF-03-01",
                  cells: [
                    {
                      place: 1,
                      number: "MF-03-01-01",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 2,
                      number: "MF-03-01-02",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 3,
                      number: "MF-03-01-03",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                  ],
                },
                {
                  level: 2,
                  levelName: "MF-03-02",
                  cells: [
                    {
                      place: 1,
                      number: "MF-03-02-01",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 2,
                      number: "MF-03-02-02",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 3,
                      number: "MF-03-02-03",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          area: 3,
          areaName: "RB",
          floor: 1,
          measurement: "Meter",
          polygon: [
            { x: 0, z: 180 },
            { x: 280, z: 180 },
            { x: 280, z: 260 },
            { x: 80, z: 260 },
            { x: 80, z: 520 },
            { x: 0, z: 520 },
          ],
          rows: [
            {
              row: 1,
              rowName: "RB-01",
              direction: "LeftToRight",
              align: "Bottom",
              measurement: "Meter",
              polygon: [
                { x: 10, z: 190 },
                { x: 270, z: 190 },
                { x: 270, z: 200 },
                { x: 10, z: 200 },
              ],
              levels: [
                {
                  level: 1,
                  levelName: "RB-01-01",
                  cells: [
                    {
                      place: 1,
                      number: "RB-01-01-01",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 2,
                      number: "RB-01-01-02",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 3,
                      number: "RB-01-01-03",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 4,
                      number: "RB-01-01-04",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 5,
                      number: "RB-01-01-05",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 6,
                      number: "RB-01-01-06",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 7,
                      number: "RB-01-01-07",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                  ],
                },
                {
                  level: 2,
                  levelName: "RB-01-02",
                  cells: [
                    {
                      place: 1,
                      number: "RB-01-02-01",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 2,
                      number: "RB-01-02-02",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 3,
                      number: "RB-01-02-03",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 4,
                      number: "RB-01-02-04",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 5,
                      number: "RB-01-02-05",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                  ],
                },
                {
                  level: 3,
                  levelName: "RB-01-03",
                  cells: [
                    {
                      place: 1,
                      number: "RB-01-03-01",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 2,
                      number: "RB-01-03-02",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 3,
                      number: "RB-01-03-03",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                  ],
                },
              ],
            },
            {
              row: 2,
              rowName: "RB-02",
              direction: "RightToLeft",
              align: "Top",
              measurement: "Meter",
              polygon: [
                { x: 10, z: 230 },
                { x: 270, z: 230 },
                { x: 270, z: 245 },
                { x: 10, z: 245 },
              ],
              levels: [
                {
                  level: 1,
                  levelName: "RB-02-01",
                  cells: [
                    {
                      place: 1,
                      number: "RB-02-01-01",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 2,
                      number: "RB-02-01-02",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 3,
                      number: "RB-02-01-03",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 4,
                      number: "RB-02-01-04",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 5,
                      number: "RB-02-01-05",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 6,
                      number: "RB-02-01-06",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 7,
                      number: "RB-02-01-07",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 8,
                      number: "RB-02-02-08",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 9,
                      number: "RB-02-02-09",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 0,
                    },
                    {
                      place: 10,
                      number: "RB-02-02-10",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                  ],
                },
                {
                  level: 2,
                  levelName: "RB-02-02",
                  cells: [
                    {
                      place: 1,
                      number: "RB-02-02-01",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 2,
                      number: "RB-02-02-02",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 3,
                      number: "RB-02-02-03",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 4,
                      number: "RB-02-02-04",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 5,
                      number: "RB-02-02-05",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 6,
                      number: "RB-02-02-06",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 7,
                      number: "RB-02-02-07",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 8,
                      number: "RB-02-02-08",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 9,
                      number: "RB-02-02-09",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                  ],
                },
                {
                  level: 3,
                  levelName: "RB-02-03",
                  cells: [
                    {
                      place: 1,
                      number: "RB-02-03-01",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 2,
                      number: "RB-02-03-02",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 3,
                      number: "RB-02-03-03",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 0,
                    },
                    {
                      place: 4,
                      number: "RB-02-03-04",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 5,
                      number: "RB-02-03-05",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 6,
                      number: "RB-02-03-06",
                      measurement: "Millimeter",
                      width: 20000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                  ],
                },
              ],
            },
            {
              row: 3,
              rowName: "RB-03",
              direction: "TopToBottom",
              align: "Right",
              measurement: "Meter",
              polygon: [
                { x: 10, z: 260 },
                { x: 25, z: 260 },
                { x: 25, z: 500 },
                { x: 10, z: 500 },
              ],
              levels: [
                {
                  level: 1,
                  levelName: "RB-03-01",
                  cells: [
                    {
                      place: 1,
                      number: "RB-03-01-01",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 2,
                      number: "RB-03-01-02",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 3,
                      number: "RB-03-01-03",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 4,
                      number: "RB-03-01-04",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 5,
                      number: "RB-03-01-05",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 6,
                      number: "RB-03-01-06",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 7,
                      number: "RB-03-01-07",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 8,
                      number: "RB-03-02-08",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 9,
                      number: "RB-03-02-09",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 0,
                    },
                    {
                      place: 10,
                      number: "RB-03-02-10",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 11,
                      number: "RB-03-02-11",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 12,
                      number: "RB-03-02-12",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 13,
                      number: "RB-03-02-13",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                  ],
                },
                {
                  level: 2,
                  levelName: "RB-03-02",
                  cells: [
                    {
                      place: 1,
                      number: "RB-03-02-01",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 2,
                      number: "RB-03-02-02",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 3,
                      number: "RB-03-02-03",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 4,
                      number: "RB-03-02-04",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 5,
                      number: "RB-03-02-05",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 6,
                      number: "RB-03-02-06",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 7,
                      number: "RB-03-02-07",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 8,
                      number: "RB-03-02-08",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 9,
                      number: "RB-03-02-09",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 10,
                      number: "RB-03-02-10",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 11,
                      number: "RB-03-02-11",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 12,
                      number: "RB-03-02-12",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                  ],
                },
                {
                  level: 3,
                  levelName: "RB-03-03",
                  cells: [
                    {
                      place: 1,
                      number: "RB-03-03-01",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 2,
                      number: "RB-03-03-02",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 3,
                      number: "RB-03-03-03",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 4,
                      number: "RB-03-03-04",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 5,
                      number: "RB-03-03-05",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 6,
                      number: "RB-03-03-06",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 7,
                      number: "RB-03-03-07",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 8,
                      number: "RB-03-03-08",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 9,
                      number: "RB-03-03-09",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 10,
                      number: "RB-03-03-10",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                  ],
                },
              ],
            },
            {
              row: 4,
              rowName: "RB-04",
              direction: "TopToBottom",
              align: "Right",
              measurement: "Meter",
              polygon: [
                { x: 40, z: 260 },
                { x: 55, z: 260 },
                { x: 55, z: 510 },
                { x: 40, z: 510 },
              ],
              levels: [
                {
                  level: 1,
                  levelName: "RB-04-01",
                  cells: [
                    {
                      place: 1,
                      number: "RB-04-01-01",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 2,
                      number: "RB-04-01-02",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 3,
                      number: "RB-04-01-03",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 4,
                      number: "RB-04-01-04",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 5,
                      number: "RB-04-01-05",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 6,
                      number: "RB-04-01-06",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 7,
                      number: "RB-04-01-07",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 8,
                      number: "RB-04-02-08",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 9,
                      number: "RB-04-02-09",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 10,
                      number: "RB-04-02-10",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 11,
                      number: "RB-04-02-11",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 12,
                      number: "RB-04-02-12",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 13,
                      number: "RB-04-02-13",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 14,
                      number: "RB-04-02-14",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 15,
                      number: "RB-04-02-15",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                  ],
                },
                {
                  level: 2,
                  levelName: "RB-04-02",
                  cells: [
                    {
                      place: 1,
                      number: "RB-04-02-01",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 2,
                      number: "RB-04-02-02",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 3,
                      number: "RB-04-02-03",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 4,
                      number: "RB-04-02-04",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 5,
                      number: "RB-04-02-05",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 6,
                      number: "RB-04-02-06",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 7,
                      number: "RB-04-02-07",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 8,
                      number: "RB-04-02-08",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 9,
                      number: "RB-04-02-09",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 10,
                      number: "RB-04-02-10",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 11,
                      number: "RB-04-02-11",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 12,
                      number: "RB-04-02-12",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                  ],
                },
                {
                  level: 3,
                  levelName: "RB-04-03",
                  cells: [
                    {
                      place: 1,
                      number: "RB-04-03-01",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 2,
                      number: "RB-04-03-02",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 3,
                      number: "RB-04-03-03",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 4,
                      number: "RB-04-03-04",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 5,
                      number: "RB-04-03-05",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 6,
                      number: "RB-04-03-06",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 7,
                      number: "RB-04-03-07",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 8,
                      number: "RB-04-03-08",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 9,
                      number: "RB-04-03-09",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 10,
                      number: "RB-04-03-10",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          area: 6,
          areaName: "RR",
          floor: 1,
          measurement: "Meter",
          polygon: [
            { x: 0, z: 620 },
            { x: 0, z: 520 },
            { x: 80, z: 520 },
            { x: 80, z: 260 },
            { x: 280, z: 260 },
            { x: 280, z: 620 },
          ],
          rows: [
            {
              row: 3,
              rowName: "RR-01",
              direction: "BottomToTop",
              align: "Center",
              measurement: "Meter",
              polygon: [
                { x: 240, z: 270 },
                { x: 260, z: 270 },
                { x: 260, z: 610 },
                { x: 240, z: 610 },
              ],
              levels: [
                {
                  level: 1,
                  levelName: "RR-01-01",
                  cells: [
                    {
                      place: 1,
                      number: "RR-01-01-01",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 2,
                      number: "RR-01-01-02",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 3,
                      number: "RR-01-01-03",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 4,
                      number: "RR-01-01-04",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 5,
                      number: "RR-01-01-05",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 6,
                      number: "RR-01-01-06",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 7,
                      number: "RR-01-01-07",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 8,
                      number: "RR-01-02-08",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 9,
                      number: "RR-01-02-09",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 0,
                    },
                    {
                      place: 10,
                      number: "RR-01-02-10",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 11,
                      number: "RR-01-02-11",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 12,
                      number: "RR-01-02-12",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 13,
                      number: "RR-01-02-13",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                  ],
                },
                {
                  level: 2,
                  levelName: "RR-01-02",
                  cells: [
                    {
                      place: 1,
                      number: "RR-01-02-01",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 2,
                      number: "RR-01-02-02",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 3,
                      number: "RR-01-02-03",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 4,
                      number: "RR-01-02-04",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 5,
                      number: "RR-01-02-05",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 6,
                      number: "RR-01-02-06",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 7,
                      number: "RR-01-02-07",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 8,
                      number: "RR-01-02-08",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 9,
                      number: "RR-01-02-09",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 10,
                      number: "RR-01-02-10",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 11,
                      number: "RR-01-02-11",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 12,
                      number: "RR-01-02-12",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                  ],
                },
                {
                  level: 3,
                  levelName: "RR-01-03",
                  cells: [
                    {
                      place: 1,
                      number: "RR-01-03-01",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 2,
                      number: "RR-01-03-02",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 3,
                      number: "RR-01-03-03",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 4,
                      number: "RR-01-03-04",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 5,
                      number: "RR-01-03-05",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 6,
                      number: "RR-01-03-06",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 7,
                      number: "RR-01-03-07",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 8,
                      number: "RR-01-03-08",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 9,
                      number: "RR-01-03-09",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                    {
                      place: 10,
                      number: "RR-01-03-10",
                      measurement: "Millimeter",
                      width: 10000,
                      height: 10000,
                      depth: 10000,
                      weight: 10000,
                      freeWeight: 10000,
                      active: 1,
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      warehouse: 2,
      warehouseName: "WR #5",
      measurement: "Meter",
      polygon: [
        { x: 0, z: 0 },
        { x: 400, z: 0 },
        { x: 400, z: 620 },
        { x: 0, z: 620 },
      ],
      areas: [
        {
          area: 4,
          areaName: "RB",
          floor: 1,
          measurement: "Meter",
          polygon: [
            { x: 0, z: 0 },
            { x: 400, z: 0 },
            { x: 400, z: 100 },
            { x: 0, z: 100 },
          ],
          rows: [],
        },
        {
          area: 5,
          areaName: "RR",
          floor: 2,
          measurement: "Meter",
          polygon: [
            { x: 0, z: 100 },
            { x: 400, z: 100 },
            { x: 400, z: 600 },
            { x: 0, z: 600 },
          ],
          rows: [],
        },
      ],
    },
  ],
};

  WH.api.getWarehouses = async function() {
    await mockDelay();

    return {
      ok: true,
      data: WAREHOUSE_MOCK_DATA,
      error: null,
    };
  };
})();